services:
  - type: web
    name: documentcrunch-event-hub
    runtime: node
    plan: starter
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: documentcrunch-production-jwt-secret-change-this-in-railway
      - key: DATABASE_PATH
        value: ./database/events.db
