services:
  - type: web
    name: documentcrunch-event-hub
    runtime: node
    plan: starter
    buildCommand: |
      # Install backend dependencies
      cd backend && npm install && cd ..
      # Install frontend dependencies and build
      cd frontend && npm install && npm run build
      # Copy built frontend to backend public folder
      mkdir -p ../backend/public
      cp -r build/* ../backend/public/
      cd ..
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: documentcrunch-production-jwt-secret-change-this-in-railway
      - key: DATABASE_PATH
        value: ./database/events.db
