services:
  - type: web
    name: documentcrunch-event-hub
    runtime: node
    region: oregon
    plan: starter
    rootDir: backend # This makes everything relative to backend/
    buildCommand: npm install # Installs in backend/
    startCommand: npm start # Runs from backend/
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: documentcrunch-production-jwt-secret-change-this-in-railway
      - key: DATABASE_PATH
        value: ./database/events.db
    disk:
      name: database
      mountPath: /opt/render/project/src/database
      sizeGB: 1
